FROM centos:7.3.1611
LABEL author="Isaac A. White <iwhite@nagios.com>"

RUN yum update -y && yum install -y epel-release
RUN yum update -y && yum install -y \
	gcc \
	glibc \
	glibc-common \
	wget \
	unzip \
	httpd \
	php \
	gd \
	gd-devel \
	perl \
	postfix \
	vim \
	git \
	make \
	supervisor \
	ntp \
	man \
	gettext \
	automake \
	autoconf \
	openssl-devel \
	net-snmp \
	net-snmp-utils \
	epel-release \
	perl-Net-SNMPd

RUN mkdir -p /var/www/html
COPY . /var/www/html
WORKDIR /var/www/html
RUN ./configure
RUN make all
RUN make install-groups-users
RUN usermod -a -G nagios apache
RUN make install
RUN make install-daemoninit
RUN systemctl enable httpd.service
RUN make install-commandmode
RUN make install-config
RUN make install-webconf

RUN htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin admin
RUN echo "ServerName localhost" >> /etc/httpd/conf/httpd.conf

RUN /usr/sbin/httpd -k start
RUN /etc/init.d/nagios start

# Must have plugins repo inside Nagios Core Repo (~/nagioscore/plugins)
# TODO: Make plugins another container.
WORKDIR /var/www/html/plugins/
# TODO: Build Plugins - Does not work in Dockerfile, but a shell script might...
#CMD [ "/bin/bash", "-c", "./tools/setup && ./configure" ]
#CMD [ "/bin/bash", "-c", "make && make install" ]
#RUN find . -exec touch {} +
WORKDIR /var/www/html

CMD /usr/bin/supervisord -c /var/www/html/supervisord.conf

