#! /bin/sh

if [ "z$1" = "z" ] ; then
	echo You must specify an architecture to build for!
	exit 1
fi

case "$1" in
	solaris)
		LD_RUN_PATH=/usr/lib:/usr/local/lib
		autoreconf
		PATH=.:..:$PATH configure --with-cgiurl=/nagios/cgi-bin \
--with-htmurl=/nagios \
--with-lockfile=/var/run/nagios.pid \
--with-nagios-user=nagios \
--with-nagios-grp=nagios \
--with-command-user=nagios \
--with-command-grp=www \
--prefix=/usr/local \
--exec-prefix=/usr/local/sbin \
--bindir=/usr/local/sbin \
--sbindir=/usr/local/lib/nagios/cgi \
--libexecdir=/usr/local/lib/nagios/plugins \
--datadir=/usr/local/share/nagios \
--sysconfdir=/etc/nagios \
--localstatedir=/var/log/nagios \
--with-mail=/usr/bin/mailx
		make pkgclean
		make all
		make pkgset
		;;
	*)
		echo Platform $1 is not currently supported
		exit 1
		;;
esac

exit 0