#!/bin/sh

# Write a command to the Nagios command file to cause
# it to enable active service checks.  This can be
# referred to as 'active' mode in a redundant monitoring
# environment.

# Notes: 
# 1) This script is not intended to be used as an 
#    event handler by itself.  Instead, it is used by other
#    event handler scripts (like the redundancy examples).
# 2) In order for Nagios to process any commands that
#    are written to the command file, you must enable
#    the check_external_commands option in the main
#    configuration file.

printfcmd="/usr/bin/printf"

CommandFile="/usr/local/nagios/var/rw/nagios.cmd"

# get the current date/time in seconds since UNIX epoch
datetime=`date +%s`

# pipe the command to the command file
`$printfcmd "[%i] START_EXECUTING_SVC_CHECKS\n" $datetime >> $CommandFile`

