FROM centos:7.7.1908
LABEL author="Isaac A. White <iwhite@nagios.com>"

RUN yum update -y && yum install -y \
    gcc \
    glibc \
    glibc-common \
    wget \
    unzip \
    php \
    gd \
    gd-devel \
    perl \
    postfix \
    vim \
    ctags \
    git \
    make \
    ntp \
    man \
    gettext \
    automake \
    autoconf \
    openssl-devel \
    net-snmp \
    net-snmp-utils \
    epel-release \
    perl-Net-SNMPd \
    gdb

RUN mkdir -p /var/www/html
RUN mkdir -p /var/www/plugins
COPY . /var/www/html
#COPY ./nagioscore /var/www/html
#COPY ./plugins /var/www/plugins
WORKDIR /var/www/html

